apiVersion: v1
kind: Service
metadata:
  name: dns-ui
  labels:
    app: dns-ui
spec:
  type: NodePort
  selector:
    app: dns-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30881
