apiVersion: v1
kind: Service
metadata:
  name: {{ include "dns-project.fullname" . }}-interceptor
  labels:
    app: dns-interceptor
spec:
  type: ClusterIP
  selector:
    app: dns-interceptor
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
