FROM node:20-alpine

WORKDIR /app

# install deps separately to leverage cache
COPY package*.json ./
RUN npm install --silent

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
